title:             Cantinho da Yara
email:             yara.prof@gmail.com
description:       Um Blog sobre música e pedagagogia
author:            "Yara Raquel"
baseurl:           ""
url:               "http://https://yararaquel.github.io"

# Social Profiles
github_username:   yararaquel
facebook_username: yararaquel.montecoelho

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
