title:             Cantinho da Yara
email:             yara.prof@gmail.com
description:       Um Blog sobre música e pedagagogia
author:            Yara Raquel
baseurl:           ""
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
