# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog da Yara
email: yara.prof@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aqui posto coisas relacionadas à Licenciatura de Música, Pedagogia e afins.
baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://yararaquel.github.io" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

google_analytics:

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "Simple Blog Theme"
  short_bio:
    en: Jekyll Blog Theme, Responsive, SEO and Facebook enabled
    it: Jekyll Blog Theme, Responsive, con SEO e integrazione Facebook
  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

#twitter:
#  username:
#instagram_username:

#linkedin_username: lorepirri

#  site:
facebook:
  publisher_id: yararaquel.montecoelho
  profile_id: yararaquel.montecoelho
  authors: [yararaquel.montecoelho]
  #pixelcode: 1670622619859349


# gitlab on site
# gitlab:
#   owner_url: https://gitlab.com/lorepirri

# # github on site
# github:
#   owner_url: https://github.com/lorepirri


# translation

t:
  en:
    latest-posts:  "Últimos Posts"
    read-more:  "Leia mais"
    on-word: "em"
    contact: "Contato"
    contact-page: "contact.md"
    read-time: "leitura mínima"
    comments: "comentários"
    go-to-home-page: "Voltar à página oficial"
    months:
      january: "Jan"
      february: "Fev"
      march: "Mar"
      april: "Abr"
      may: "Mai"
      june: "Jun"
      july: "Jul"
      august: "Ago"
      september: "Set"
      october: "Out"
      november: "Nov"
      december : "Dez"

defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles
